GET http://localhost:2410/test

####GET####
GET http://localhost:2410/products

##########
GET http://localhost:2410/products/1

########

POST http://localhost:2410/orders
Content-Type: application/json

{
  "email": "lukas.semler@gmail.com",
  "telfonnummer": "+43 660 3914245",
  "vornameEltern": "Jane ",
  "nachnameEltern": "Doe",
  "vornameSpieler": "Lukas ",
  "nachnameSpieler": "Semler",
  "summe": 26.79,
  "jahrgang": "U13",
  "prods": [
    {
      "p_id": 12,
      "name": "Wave 26 Shorts Erwachsene",
      "explaination": "Leider gibt es zu diesem Produkt noch keine Beschreibung :(",
      "price": "16.79",
      "color": "Schwarz",
      "number": "2003656-01",
      "image": "ProductImages/Wave 26 Shorts Erwachsene.jpeg",
      "category": "Player",
      "actualSize": "152",
      "anzahl": "1"
    },
      {
      "p_id": 2,
      "name": "Name 2",
      "explaination": "Leider gibt es zu diesem Produkt noch keine Beschreibung :(",
      "price": "10",
      "color": "Schwarz",
      "number": "2003656-01",
      "image": "ProductImages/Wave 26 Shorts Erwachsene.jpeg",
      "category": "Player",
      "actualSize": "152",
      "anzahl": "2"
    }
  ]
}

#######


GET http://localhost:2410/orders

#######


DELETE http://localhost:2410/products/21

######

GET http://localhost:2410/exportOrders


######

POST http://localhost:2410/login
Content-Type: application/json

{
  "email": "admin@handball-westwien.at",
  "password": "admin"
}

#####
POST http://localhost:2410/products
Content-Type: application/json

{
  "name": "Hoodie",
  "artikelNummer": "ABCDEFG",
  "farbe": "Grau",
  "preis": "29.99",
  "groessen": [ "XL", "L", "M" ],
  "imageSchicken": { "datentyp": "jpeg" },
  "linkImage": "/images/Hoodie.jpeg",
  "category": { "id": 1, "name": "Casual" }
}

########
GET http://localhost:2410/products/1

########

POST http://localhost:2410/person
Content-Type: application/json

{
  "vorname": "Seppo",
  "nachname": "Frimmel",
  "email": "",
  "telefonnummer": "",
  "birthdate": "2015-08-13T18:30:00.000Z",
  "eintritt": "2024-08-10T18:31:00.000Z",
  "street": "Linzerstrasse",
  "houseNumber": "111",
  "postalCode": "1140",
  "city": "Wien",
  "newsletter": true,
  "notes": "",
  "rollen": [
    "Spieler"
  ],
  "player_infos": {
    "mitgliederbeitragssumme": "250",
    "mannschaft": {
      "mannschaftid": 1,
      "mannschaftsname": "Mondweg",
      "jahrgang": null,
      "anzahlspieler": "1",
      "anzahleltern": "1"
    }
  },
  "parents": [
    {
      "vorname": "Roman",
      "nachname": "Frimmel",
      "email": "roman@gmail.com",
      "telefonnummer": "06603914245",
      "birthdate": null,
      "same_adress": true,
      "street": "Linzerstrasse",
      "houseNumber": "111",
      "postalCode": "1140",
      "city": "Wien",
      "newsletter": true,
      "notes": "",
      "rollen": [
        "Eltern"
      ]
    },
    {
      "vorname": "Birgit",
      "nachname": "Frimmel",
      "email": "frimmel@gmail.com",
      "telefonnummer": "06603914245",
      "birthdate": null,
      "same_adress": true,
      "street": "Linzerstrasse",
      "houseNumber": "111",
      "postalCode": "1140",
      "city": "Wien",
      "newsletter": true,
      "notes": "",
      "rollen": [
        "Eltern"
      ]
    }
  ]
}


####
POST http://localhost:2410/spendePay
Content-Type: application/json

{
  "vorname": "Benjamin",
  "nachname": "Stauf",

  "email": "Benjamin@stauf.at",
  "telefonnummer": "+43650 2821919",

  "strasse": "Mörikeweg ",
  "hausnr": "20a/5",
  "plz": "1160",
  "ort": "Wien",

  "geburtsdatum": "2003-10-24",
  "spendenwert": "9.99"
}


####
POST http://localhost:2410/orderTicket
Content-Type: application/json

{
  "vorname": "Lukas",
  "nachname": "Semler",
  "email": "lukas.semler@gmail.com",
  "telefonnummer": "06603914245",
  "strasse": "Venusweg 11",
  "hausnr": "11",
  "plz": "1140",
  "ort": "Wien",
  "geburtsdatum": "",
  "spendenwert": "",
  "saisonkarten": {
    "id": 1,
    "title": "Saisonkarte normal",
    "description": "Normale Saisonkarte",
    "users": 140,
    "verification": false
  },
  "anzahl": {
    "id": 2,
    "name": "2"
  },
  "summe": 280
}

#######

GET http://localhost:2410/mannschaften


####
GET http://localhost:2410/MitgliedsbeitragAll